// orders.service.ts - Service for managing order data and API interactions
// Handles creating and managing orders from the mock API

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, catchError, of } from 'rxjs';

// Type definition for Order object structure
export type Order = {
    id?: string; // Auto-generated by MockAPI
    orderNumber: string; // Unique order identifier
    orderDate: string; // ISO date string
    status: 'confirmed' | 'processing' | 'shipped' | 'delivered';
    customerEmail: string | null;
    customerName: string | null;
    items: OrderItem[];
    totalItems: number;
    subtotal: number;
    totalAmount: number;
    currency: string;
    createdAt?: string;
    updatedAt?: string;
};

// Type for individual order items
export type OrderItem = {
    productId: string;
    productTitle: string;
    productThumbnail: string;
    quantity: number;
    unitPrice: number;
    currency: string;
};

// Service class for order-related operations
@Injectable({ providedIn: 'root' })
export class OrdersService {
    private readonly baseUrl = 'https://699dd36183e60a406a4787b2.mockapi.io/Orders';

    constructor(private http: HttpClient) { }

    // Create a new order
    createOrder(order: Omit<Order, 'id' | 'createdAt' | 'updatedAt'>): Observable<Order | null> {
        return this.http.post<Order>(this.baseUrl, order).pipe(
            catchError((error) => {
                console.error('Error creating order:', error);
                return of(null);
            })
        );
    }

    // Get all orders (for admin purposes)
    getOrders(): Observable<Order[]> {
        return this.http.get<Order[]>(this.baseUrl).pipe(
            catchError((error) => {
                console.error('Error fetching orders:', error);
                return of([]);
            })
        );
    }

    // Get orders by customer email
    getOrdersByCustomer(email: string): Observable<Order[]> {
        return this.http.get<Order[]>(`${this.baseUrl}?customerEmail=${email}`).pipe(
            catchError((error) => {
                console.error('Error fetching customer orders:', error);
                return of([]);
            })
        );
    }

    // Generate unique order number
    generateOrderNumber(): string {
        const timestamp = Date.now();
        const random = Math.floor(Math.random() * 1000).toString().padStart(3, '0');
        return `ORD-${new Date().getFullYear()}-${random}`;
    }
}